# fly.toml app configuration file generated for daniel-varga on 2023-07-18T13:27:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "daniel-varga"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
